# .github/workflows/pages.yml
name: Publish glossary to Pages
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare site
        run: |
          rm -rf docs
          mkdir -p docs/assets docs/glossary
          cp index.html docs/
          cp -r assets/* docs/assets/
          cp -r glossary/* docs/glossary/
          touch docs/.nojekyll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
